version: '3.3'
services:
  users:
    build: './users'
    restart: on-failure
    ports:
      - "3000:3000"

  club:
    build: './club'
    restart: on-failure
    ports:
      - "3001:3000"

  event:
    build: './event'
    restart: on-failure
    ports:
      - "3002:3000"

  social:
    build: './social'
    restart: on-failure
    ports:
      - "3003:3000"

  ticket:
    build: './ticket'
    restart: on-failure
    ports:
      - "3004:3000"

  chat:
    build: './chat'
    restart: on-failure
    ports:
      - "3005:3000"

  admin:
    build: './admin'
    restart: on-failure
    ports:
      - "3006:3000"

  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - club
      - users
      - event
      - social
      - ticket
      - chat
      - admin