const EMAIL_EXISTS = "EMAIL_EXISTS";
const USERNAME_EXISTS = "USERNAME_EXISTS";
const LOGIN_FAILED = "LOGIN_FAILED";
const USER_NOT_FOUND = "USER_NOT_FOUND";

const CITY_JOHANNESBURG = "johannesburg";

const INVALID_PURCHASE_REFERENCE = "INVALID_PURCHASE_REFERENCE";
const TRANSACTION_NOT_SUCCESSFUL = "TRANSACTION_NOT_SUCCESSFUL";

const POST_TYPE_IMAGE = "POST_TYPE_IMAGE";
const POST_TYPE_VIDEO = "POST_TYPE_VIDEO";

exports.LOGIN_FAILED = LOGIN_FAILED
exports.EMAIL_EXISTS = EMAIL_EXISTS
exports.USERNAME_EXISTS = USERNAME_EXISTS
exports.USER_NOT_FOUND = USER_NOT_FOUND
exports.CITY_JOHANNESBURG = CITY_JOHANNESBURG
exports.INVALID_PURCHASE_REFERENCE = INVALID_PURCHASE_REFERENCE
exports.TRANSACTION_NOT_SUCCESSFUL = TRANSACTION_NOT_SUCCESSFUL
exports.POST_TYPE_IMAGE = POST_TYPE_IMAGE
exports.POST_TYPE_VIDEO = POST_TYPE_VIDEO